src/WebApp/ViewModels/BusinessActivityIdViewModel.cs
namespace BusinessActivities.WebApp.ViewModels
{
    public class BusinessActivityIdViewModel
    {
        public string Id { get; set; }
    }
}

src/WebApp/ViewModels/BusinessActivitySearchViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BusinessActivities.WebApp.ViewModels
{
    /// <summary>
    /// Represents view model for searching for business activity.
    /// </summary>
    public class BusinessActivitySearchViewModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessActivitySearchViewModel"/>
        /// class.
        /// </summary>
        public BusinessActivitySearchViewModel()
        {

        }

        /// <summary>
        /// Gets or sets the city name.
        /// </summary>
        [Display(Name = "Miasto")]
        public string City { get; set; }

        /// <summary>
        /// Gets or sets the id used for searching.
        /// </summary>
        [Display(Name = "KRS, NIP lub REGON")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets the National Court Register (KRS) number.
        /// <para/>
        /// KRS is a ten-digit number from public register, maintained
        /// by selected district courts and Polish Ministry of Justice.
        /// </summary>
        [Display(Name = "KRS")]
        public string Krs { get; set; }

        /// <summary>
        /// Gets or sets the business name.
        /// </summary>
        [Display(Name = "Nazwa")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Tax Identification Number (NIP).
        /// <para/>
        /// NIP is a ten-digit code used to identify taxpayers in Poland.
        /// </summary>
        [Display(Name = "NIP")]
        public string Nip { get; set; }

        /// <summary>
        /// Gets or sets the postal code.
        /// </summary>
        [Display(Name = "Kod pocztowy")]
        public string PostalCode { get; set; }

        /// <summary>
        /// Gets or sets the Register of National Economy (REGON) number.
        /// <para/>
        /// REGON is a nine-digit number of subject from Register of National Economy.
        /// </summary>
        [Display(Name = "REGON")]
        public string Regon { get; set; }

        /// <summary>
        /// Gets or sets the name of the street.
        /// </summary>
        [Display(Name = "Ulica")]
        public string Street { get; set; }

        /// <summary>
        /// Gets or sets the street number.
        /// </summary>
        [Display(Name = "Numer")]
        public string StreetNumber { get; set; }
    }
}

src/WebApp/ViewModels/ErrorViewModel.cs
using System;

namespace BusinessActivities.WebApp.ViewModels
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/WebApp/Controllers/BusinessActivitiesController.cs
using BusinessActivities.WebApp.Services;
using BusinessActivities.WebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;
using System.Threading.Tasks;

namespace BusinessActivities.WebApp.Controllers
{
    public class BusinessActivitiesController : Controller
    {
        private readonly BusinessActivitiesManager _manager;

        public BusinessActivitiesController(BusinessActivitiesManager manager)
        {
            _manager = manager;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] BusinessActivityIdViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var (response, resultViewModel) = await _manager.GetAsync<BusinessActivitySearchViewModel>(viewModel.Id);
            if (response.StatusCode == HttpStatusCode.NotFound)
            {
                ViewBag.ErrorMessage = "Brak wyników.";
            }
            if (response.StatusCode == HttpStatusCode.BadRequest)
            {
                ViewBag.ErrorMessage = "Zły format.";
            }

            return PartialView("_Model", resultViewModel);
        }
    }
}

src/WebApp/Controllers/HomeController.cs
using BusinessActivities.WebApp.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BusinessActivities.WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/WebApp/Views/BusinessActivities/_Model.cshtml
@model BusinessActivitySearchViewModel

<div id="errorMessageBody">@ViewBag.ErrorMessage</div>
<div id="modelBody">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label asp-for="Krs"></label>
        <input asp-for="Krs" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label asp-for="Nip"></label>
        <input asp-for="Nip" class="form-control" readonly>
    </div>

    <div class="form-group">
        <label asp-for="Regon"></label>
        <input asp-for="Regon" class="form-control" readonly>
    </div>

    <div class="row justify-content-center">
        <div class="col-xs-12 col-sm-9">
            <div class="form-group">
                <label asp-for="Street"></label>
                <input asp-for="Street" class="form-control" readonly>
            </div>
        </div>
        <div class="col-xs-12 col-sm-3">
            <div class="form-group">
                <label asp-for="StreetNumber"></label>
                <input asp-for="StreetNumber" class="form-control" readonly>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-xs-12 col-sm-4">
            <div class="form-group">
                <label asp-for="PostalCode"></label>
                <input asp-for="PostalCode" class="form-control" readonly>
            </div>
        </div>
        <div class="col-xs-12 col-sm-8">
            <div class="form-group">
                <label asp-for="City"></label>
                <input asp-for="City" class="form-control" readonly>
            </div>
        </div>
    </div>
</div>

src/WebApp/Views/Home/Index.cshtml
@model BusinessActivitySearchViewModel
@{
    ViewData["Title"] = "Wyszukaj firmę";
}

<div class="row justify-content-center">
    <div class="col">
        <h1 class="display-4 text-center break-word">@ViewData["Title"]</h1>
    </div>
</div>

<hr class="my-3" />

<div class="row justify-content-center">
    <div class="col-sm-12 col-md-5 col-lg-4 col-xl-3">

        <form id="searchForm" asp-controller="BusinessActivities" asp-action="@nameof(BusinessActivitiesController.Index)">
            <div class="form-group">
                <label asp-for="Id"></label>
                <input asp-for="Id" id="searchInput" class="form-control">
                <span asp-validation-for="Id"></span>
            </div>
        </form>

        <button id="sendButton" class="btn btn-success btn-lg" type="button">
            <i class="fas fa-search pr-1"></i>
            Szukaj
        </button>

        <h5 id="errorMessage" class="my-3 text-danger"></h5>

    </div>
    <div class="col-sm-12 col-md-6 col-lg-5 col-xl-5 align-self-center">
        <div class="alert alert-info my-3">
            W pole wyszukiwarki można wprowadzić jeden z trzech numerów:
            <ul>
                <li>
                    KRS &mdash; 10-cyfrowy numer;
                </li>
                <li>
                    NIP &mdash; 10-cyfrowy numer z opcjonalnym prefiksem "PL" lub trzema myślnikami w środku np. 725-18-01-126;
                </li>
                <li>
                    REGON &mdash; 9-cyfrowy numer.
                </li>
            </ul>
        </div>
    </div>
</div>

<hr class="my-3" />

<div class="row justify-content-center">
    <div class="col-sm-12 col-md-10 col-lg-8 col-xl-6">

        <div id="model"></div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/bootstrap.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/all.css"
              integrity="sha256-BbA16MRVnPLkcJWY/l5MsqhyOIQr7OpgUAkYkKVvYco="
              crossorigin="anonymous" />
    </environment>

</head>
<body>
    <header>
        <nav class="navbar navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">WebApp</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WebApp
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/bootstrap.bundle.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                integrity="sha256-BJeo0qm959uMBGb65z40ejJYGSgR7REI4+CW1fNKwOg="
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                integrity="sha256-fzFFyH01cBVPYzl16KT40wqjhgPtq6FFUB6ckN2+GGw="
                crossorigin="anonymous"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>